import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import QueryContext from "@/components/queryContext/QueryContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App Masters",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-bt">
      <QueryContext>
        <body className={inter.className}>{children}</body>
      </QueryContext>
    </html>
  );
}
